'use strict'
export showUserData from './showUserData.js'
export changePsw from './changePsw.js'
export physicalList from './physicalList.js'
export diagnosisList from './diagnosisList.js'
export userBlog from './userBlog.js'
export userBlogList from './userBlogList.js'
export newDiagnosis from './newDiagnosis.js'
export newPhysical from './newPhysical.js'
export myBlogList from './myBlogList.js'
export userShowDrugs from './userShowDrugs.js'