'use strict'
export ToDoo from './ToDoo.js'
export showUsers from './showUsers.js'
export showAdmin from './showAdmin.js'
export modifyUser from './modifyUser.js'
export addAdmin from './addAdmin.js'  
export addNotice from './addNotice.js'
export addHealthKnowledge from './addHealthKnowledge.js'
export addDrugs from './addDrugs.js'
export showNotice from './showNotice.js'
export showHealthKnowledge from './showHealthKnowledge.js'
export showDrugs from './showDrugs.js'
export showHospital from './showHospital.js'
export addHospital from './addHospital.js'
export editDrugs from './editDrugs.js'
//export showUserData from './usercenter/showUserData.js'